Rename posix_close() for improved musl compilation
Renames the posix_close() function used by sysdep_posix.c to posix_closex() to
avoid conflicting with an identical named function in musl's unistd.h header
file.

Without this change, running `CC=musl-gcc configure && make` fails to compile
the project due to the following error:

-------------------------------------------------

sysdep_posix.c:82:1: error: conflicting types for ‘posix_close’
 posix_close(void *rh)
 ^~~~~~~~~~~
In file included from sysdep_posix.c:20:
/usr/include/x86_64-linux-musl/unistd.h:38:5: note: previous declaration of ‘posix_close’ was here
 int posix_close(int, int);
     ^~~~~~~~~~~

-------------------------------------------------

Because this function name is only used between where it is called elsewhere in
the program and the function's implementation (which then calls unistd.h's
close()), the name of the function doesn't actually matter: renaming it
something like posix_closex() is a reasonable change that doesn't really need
to be guarded by an #ifdef'd macro.

Cherry-picked from [2] (then split up and updated the commit, and reworded this
commit message)

[1] https://sourceforge.net/p/partclone-utils/git/merge-requests/4/

[2] https://git.code.sf.net/u/mcavoys/partclone-utils add-musl-fixes branch